### ISSUE TITLE
omega-h@develop build failure [via spack] with intel compilers

### ISSUE THREAD

**Issue by balay** [SNLComputation/omega_h#293]
This issue is at d1aa5a5c975597b933e145bb26b5b477197e45ec

Attaching build log
[spack-build.out.txt](https://github.com/SNLComputation/omega_h/files/2834402/spack-build.out.txt)

**Comment by ibaned** [comment]
@balay I just pushed a possible fix. Could you let me know if it worked? Thanks!

**Comment by balay** [comment]
Yes the fix works. Thanks!

I see the fix is in develop branch. However omega-h@develop uses master branch. I guess at some point the fix will get into master branch.

**Comment by ibaned** [comment]
Yep! I was just waiting for your confirmation
