### ISSUE TITLE
accumulating to vertices from bounded elements

### ISSUE THREAD

**Issue by cwsmith** [SNLComputation/omega_h#296]
Is there a better way to accumulate values to vertices from the elements that bound them?  Here is my potentially naive attempt:
https://github.com/cwsmith/omega_h/blob/elms2verts/example/elmToVtx/main.cpp

Thank you.

**Comment by ibaned** [comment]
Sorry for not seeing this earlier!

Yes, this is how I always do it.

One small detail that will help performance: use a local variable for the vertex value, do `+=` into that local variable, then assign the local variable into the array at the end.

**Comment by ibaned** [comment]
Going to close this as answered, please comment if there are follow-up questions.
