### ISSUE TITLE
Compilation error with nvcc (../kokkos/install/bin/nvcc_wrapper -- broken)

### ISSUE THREAD

**Issue by kriezh** [SNLComputation/omega_h#303]
Hi, 
Me and my colleague, we manage to installed the omega_h on the local cluster, where we do not have root permission. We are trying to run the FEniCS, so we have activated the FEniCS from the anaconda installation, and it worked!

Now we would like to try GPU, have also installed the kokkos as per the instructions:

`git clone https://github.com/kokkos/kokkos.git
cd kokkos/
mkdir build
cd build/
source ../generate_makefile.bash --prefix=/cfs/klemming/nobackup/k/kriezh/kokkos/install
make kokkoslib
make install`

and then, we did cmake  like this:

`cmake /cfs/klemming/nobackup/k/kriezh/omega_h -DBUILD_TESTING:BOOL="ON" -DCMAKE_INSTALL_PREFIX:PATH="/cfs/klemming/nobackup/k/kriezh/omega_h/install_gpu" -DOmega_h_EXAMPLES:BOOL="ON" -DOmega_h_USE_pybind11:BOOL="OFF" -DOmega_h_USE_MPI:BOOL="ON" -DOmega_h_USE_OpenMP:BOOL="OFF" -DOmega_h_USE_CUDA:BOOL="ON" -DOmega_h_ARCH:STRING="" -DOmega_h_USE_DOLFIN:BOOL="ON" -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=/cfs/klemming/nobackup/k/kriezh/kokkos/install/bin/nvcc_wrapper -DOmega_h_USE_Trilinos:BOOL="ON" -DTrilinos_PREFIX=/cfs/klemming/nobackup/k/kriezh/kokkos`

and this is the error we are getting:
`-- The CXX compiler identification is GNU 7.2.0
-- Check for working CXX compiler: /cfs/klemming/nobackup/k/kriezh/kokkos/install/bin/nvcc_wrapper
-- Check for working CXX compiler: /cfs/klemming/nobackup/k/kriezh/kokkos/install/bin/nvcc_wrapper -- broken
CMake Error at /cfs/klemming/nobackup/k/kriezh/anconda3_installation/envs/fenicsproject/share/cmake-3.14/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "/cfs/klemming/nobackup/k/kriezh/kokkos/install/bin/nvcc_wrapper"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /cfs/klemming/nobackup/k/kriezh/omega_h/build_GPU/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake cmTC_5ffbe/fast 
    /usr/bin/gmake -f CMakeFiles/cmTC_5ffbe.dir/build.make CMakeFiles/cmTC_5ffbe.dir/build
    gmake[1]: Entering directory `/cfs/klemming/nobackup/k/kriezh/omega_h/build_GPU/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_5ffbe.dir/testCXXCompiler.cxx.o
    /cfs/klemming/nobackup/k/kriezh/kokkos/install/bin/nvcc_wrapper    -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe    -o CMakeFiles/cmTC_5ffbe.dir/testCXXCompiler.cxx.o -c /cfs/klemming/nobackup/k/kriezh/omega_h/build_GPU/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    nvcc fatal   : Value 'c++17' is not defined for option 'std'
    gmake[1]: *** [CMakeFiles/cmTC_5ffbe.dir/testCXXCompiler.cxx.o] Error 1
    gmake[1]: Leaving directory `/cfs/klemming/nobackup/k/kriezh/omega_h/build_GPU/CMakeFiles/CMakeTmp'
    gmake: *** [cmTC_5ffbe/fast] Error 2
   
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

-- Configuring incomplete, errors occurred!
See also "/cfs/klemming/nobackup/k/kriezh/omega_h/build_GPU/CMakeFiles/CMakeOutput.log".
See also "/cfs/klemming/nobackup/k/kriezh/omega_h/build_GPU/CMakeFiles/CMakeError.log".

Could you please help this out!

These are the loaded modules:
(fenicsproject) tegner-login-1$ module list 
Currently Loaded Modulefiles:
 1) gcc/7.2.0 2) cuda/10.0

**Comment by ibaned** [comment]
CUDA doesn't support C++17, so you can't pass the `-std=c++17` flag when compiling Omega_h with CUDA.
