### ISSUE TITLE
CMake minimum version required is 3.7, not 3.0

### ISSUE THREAD

**Issue by tristan0x** [SNLComputation/omega_h#311]
Currently, CMake 3.0.0 or higher is supposed to be supported according to `cmake_minimum_version` but:
* *bob.cmake* uses `cmake_parse_arguments` which has been introduced in 3.5
* top-level *CMakeLists.txt* uses `VERSION_GREATER_EQUAL` *if* operator introduced in 3.7

**Comment by ibaned** [comment]
I guess we should be honest and declare `3.7` in the top-level `CMakeLists.txt`?

**Comment by ibaned** [comment]
I just pushed this to develop
