### ISSUE TITLE
Moving mesh support

### ISSUE THREAD

**Issue by tamaradanceva** [SNLComputation/omega_h#314]
Hi, I am working on an FSI problem and I was wondering if Omega_h supports moving meshes. If yes, could you please point me to the mesh movement source files and possibly some examples? I have looked in the issues and the code but so far I haven't been able to find what I am looking for. Many thanks, Tamara

**Comment by tamaradanceva** [comment]
I might have answered my own question, simply setting the coordinates with set_coords will work I guess. In any case, if there is an example somewhere it would be useful.

**Comment by ibaned** [comment]
Yes, setting coordinates and calling `adapt` as needed is a good approach that works in a moving mesh code that I develop. There are cases in which the movement of one time step can invert an element, in which case `warp_to_limit` can help, but depending on the design of your code that many not be a concern (our finite element formulation does not allow inverting in one time step).

**Comment by tamaradanceva** [comment]
Thanks a lot for the help again! I will try and see. Closing the issue.
