### ISSUE TITLE
compile failures with gcc-9.0.1 (via spack/xsdk)

### ISSUE THREAD

**Issue by balay** [SNLComputation/omega_h#316]
Both omega-h@develop and omega-h@9.19.1 fail to build with gcc-9.0.1 on fedora-30 [via spack/xsdk]

Attaching logs
[omega-h-9.19.1-spack-build.out.txt](https://github.com/SNLComputation/omega_h/files/3286929/omega-h-9.19.1-spack-build.out.txt)
[omega-h-develop-spack-build.out.txt](https://github.com/SNLComputation/omega_h/files/3286930/omega-h-develop-spack-build.out.txt)

**Comment by ibaned** [comment]
@balay I fixed several of these in the latest develop and release `9.27.1`. Please let me know if that release still has compile errors with GCC 9.0.1.

**Comment by ibaned** [comment]
Assuming this is resolved. Please comment if not.

**Comment by balay** [comment]
omega_h@develop%gcc@9.0.1 now builds fine.

Thanks!
