### ISSUE TITLE
xl compiler error in random123

### ISSUE THREAD

**Issue by cwsmith** [SNLComputation/omega_h#323]
Compiling Omega_h 9.29.0 (a94d891) with IBM XL (on llnl lassen)  fails in `tpl/random123` with the following error:

```
In file included from omega_h/src/Omega_h_random.cpp:3:
In file included from omega_h/src/Omega_h_random_inline.hpp:4:
In file included from omega_h/tpl/random123/philox.h:37:
In file included from omega_h/tpl/random123/features/compilerfeatures.h:199:
In file included from omega_h/tpl/random123/features/nvccfeatures.h:123:
omega_h/tpl/random123/features/gccfeatures.h:39:10: fatal error: 'ppu_intrinsics.h' file not found
#include <ppu_intrinsics.h>
         ^~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/omega_h.dir/Omega_h_random.cpp.o] Error 1
```

From what I understand `random123` wants to use a header from the [GCC toolchain (?)](https://github.com/gcc-mirror/gcc/blob/41d6b10e96a1de98e90a7c0378437c3255814b16/gcc/config/powerpcspe/ppu_intrinsics.h) that do not exist with the XL compiler paths/config.  

```
$ xlC_r --version
IBM XL C/C++ for Linux, V16.1.1 (5725-C73, 5765-J13)
Version: 16.01.0001.0005
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:52_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

Adding `-I/usr/tce/packages/gcc/gcc-7.3.1/rh/usr/lib/gcc/ppc64le-redhat-linux/7/include/` (where lassen has the gcc files installed) to the compile line results in a whole bunch of 'scary' parsing errors.

**Comment by ibaned** [comment]
So this code controls the include of `gccfeatures.h`:
```c
#if defined(__OPENCL_VERSION__) && __OPENCL_VERSION__ > 0
#include <random123/features/openclfeatures.h>
#elif defined(__CUDACC__)
#include <random123/features/nvccfeatures.h>
#elif defined(__ICC)
#include <random123/features/iccfeatures.h>
#elif defined(__xlC__)
#include <random123/features/xlcfeatures.h>
#elif defined(__SUNPRO_C) || defined(__SUNPRO_CC)
#include <random123/features/sunprofeatures.h>
#elif defined(__OPEN64__)
#include <random123/features/open64features.h>
#elif defined(__clang__)
#include <random123/features/clangfeatures.h>
#elif defined(__GNUC__)
#include <random123/features/gccfeatures.h>
#elif defined(__PGI)
#include <random123/features/pgccfeatures.h>
#elif defined(_MSC_FULL_VER)
#include <random123/features/msvcfeatures.h>
#else
#error "Can't identify compiler.  You'll need to add a new xxfeatures.hpp"
#endif
```
I assume it should have gone down the `__xlC__` path instead?

Based on [this question](https://stackoverflow.com/questions/51604239/what-happened-to-ibm-xl-c-c-preprocessor-macros), it seems like `__xlC__` might be deprecated in some sense. If their answer is correct, adding `-qxlcompatmacros` to the compiler flags should help. I will also push a change to this code to change `__xlC__` to `__ibmxl__`.

**Comment by ibaned** [comment]
The second change is in the `develop` branch if you want to try it.

**Comment by cwsmith** [comment]
I compiled with the develop branch and hit the same error.

The compiler goes from `compilefeatures.h` to `nvccfeatures.h` here:
https://github.com/SNLComputation/omega_h/blob/a94d8910d02a4a3152908fa2beb44f408c60d3e8/tpl/random123/features/compilerfeatures.h#L195-L199
then from `nvccfeatures.h` to `gccfeatures.h` here:
https://github.com/SNLComputation/omega_h/blob/a94d8910d02a4a3152908fa2beb44f408c60d3e8/tpl/random123/features/nvccfeatures.h#L122-L123
and then hits the problematic inclusion of `ppu_intrinsics.h`:
https://github.com/SNLComputation/omega_h/blob/a94d8910d02a4a3152908fa2beb44f408c60d3e8/tpl/random123/features/gccfeatures.h#L38-L40

For use of random123 on the GPU the `compilefeatures.h` to `nvccfeatures.h` switch correctly selects the device (nvcc) compiler macros/settings over the host compiler (gcc,xl,icc,etc.).  Am I understanding the use of random123 correctly in omega_h when kokkos+cuda are enabled?

**Comment by ibaned** [comment]
It seems like this code assumes that when using NVCC, the only two host compiler options are GCC and MSVC. It doesn’t seem to allow for the possibility of XL+NVCC. Do you have a particular reason for wanting to use XL anyways? I try to prefer open compilers over vendor-specific ones. We can try to add an XL+NVCC case in this header if you really want, but I just don't know if taxpayer dollars are best spent on XL support.

**Comment by cwsmith** [comment]
Nope, there is currently no specific need for an XL build.  GCC 4.9.3 is working.  I'll close the ticket.
