### ISSUE TITLE
Shape Function API

### ISSUE THREAD

**Issue by Aiteta** [SNLComputation/omega_h#358]
Does omega_h explicitly define shape functions, or does it never need them as everything is assumed to be linear? If so where is it? Can you inquire for a certain parametric coordinate and get back the field's value?

**Comment by ibaned** [comment]
Omega_h assumes linear elements in any geometric calculations it does, so no effort has been put into any code architecture or design for shape functions in general.

**Comment by Aiteta** [comment]
Thank you very much Dr. Ibanez.
