### ISSUE TITLE
omega_h as part of a cmake project

### ISSUE THREAD

**Issue by castigli** [SNLComputation/omega_h#365]
Hi!

I was wondering if incorporating `omega_h` in a `cmake` project is a feature that is intended to be supported by the library.
If this is the case, I would suggest to replace  `BUILD_TESTING` in the `bob.cmake` (and relevant occurrences) with `${PROJECT_NAME}_BUILD_TESTING` to avoid the parent project `BUILD_TESTING` drive the `omega_h` specific flag.

**Comment by ibaned** [comment]
Omega_h is only designed to be built and installed on its own, not as a CMake subdirectory of a larger project
